### ISSUE TITLE
"Mob of Me" Minecraft earth mob request

### ISSUE THREAD

**Issue by WilliamBlaze** [DereC4/derecearthmod#11]
This is a request for the Minecraft earth mob called "Mob of Me"

The full details of the original Minecraft earth Mob I speak of can be found in the wiki here at this link
https://minecraft.gamepedia.com/Minecraft_Earth:Mob_of_Me

**Comment by SacredSpirit123** [comment]
Does the mob of me copy your skin like it does in Minecraft earth?

**Comment by DereC4** [comment]
There will be a guide later
