### ISSUE TITLE
Furnace Golem Tweaks

### ISSUE THREAD

**Issue by SacredSpirit123** [DereC4/derecearthmod#13]
🎁 **Furnace Golem Tweaks**

📝 New additions to Furnace Golem behavior

🥟 Should set enemies it strikes on fire, like it does in MCE, and also probably periodically drop torches in front of the player, since the MCE Furnace Golem hands out torches like Iron Golems give poppies as gifts to people they like. Should also be extinguished when calm and ignited when angry (if it isn’t already, see the wiki page for more info)

❓ Seen here: https://minecraft.gamepedia.com/Minecraft_Earth:Furnace_Golem

**Comment by DereC4** [comment]
Will work on this and try to get it out next update

**Comment by SacredSpirit123** [comment]
Cool! Should I try to find a gameplay video for it like I did with the others?

**Comment by DereC4** [comment]
nah it's fine since i can see how to do this

**Comment by SacredSpirit123** [comment]
Well, here it is anyway! :P https://youtu.be/vKz9_rCH5t0

Sorry, when I found it, it was too cool not to share.

**Comment by SacredSpirit123** [comment]
Got some info on Melon Golems too, in case you want to see if you can adapt the changing faces or anything: https://youtu.be/uZF8c069AYE

**Comment by DereC4** [comment]
k new update adds this

**Comment by SacredSpirit123** [comment]
So did all the new features for the furnace golem get added? Did you see my comment about melon golems? Also, I’m really excited about this mod, you’re making great progress!

**Comment by DereC4** [comment]
Nice
