### ISSUE TITLE
Evolved Zombie 2: Lobber Zombie

### ISSUE THREAD

**Issue by SacredSpirit123** [DereC4/derecearthmod#17]
🎁 **Lobber Zombie**

📝 Another evolved form of Zombie, this one is a ranged combatant.

⭐ A more decayed type of Zombie, it also has lankier arms and a bad attitude. It can tear chunks of rotten flesh out of itself and throw them at prey.

🥟 Possesses a ranged attack where it has a special animation of throwing damaging rotten flesh at the enemy. This attack has strong knockback.

❓ Wiki page [here](https://minecraft.gamepedia.com/Minecraft_Earth:Lobber_Zombie) and gameplay clip [here](https://gfycat.com/unlawfulinconsequentialharrierhawk).

**Comment by DereC4** [comment]
The combat is implementable as is the mob. The animation part I really want to try but it'll take a while since animations are fairly new to me.

**Comment by DereC4** [comment]
could you make another issue for the animation i can work on that sometime later but main mob is added

**Comment by SacredSpirit123** [comment]
> could you make another issue for the animation i can work on that sometime later but main mob is added

No prob, doing it now.
