### ISSUE TITLE
Moolip (Moobloom subspecies)

### ISSUE THREAD

**Issue by SacredSpirit123** [DereC4/derecearthmod#21]
🎁 **Moolip**

📝 Description
A subspecies of Moobloom, which leaves a trail of assorted pink flower species instead of yellow ones. You could also probably milk it for a potion like you did in your mod with the Moobloom.

⭐ Describe what the mob is like
A pink Mooshroom / Moobloom with [Pink Daisies](https://minecraft.gamepedia.com/Minecraft_Earth:Pink_Daisy) sprouting from its back.

🥟 Any special features it has from Minecraft Earth?
Creates a trail of pink flower species (aliums, lilacs, and peonies, percentage of each listed on the wiki below) where it walks, and can be shorn for pink daisies.

❓ [Wiki page](https://minecraft.gamepedia.com/Minecraft_Earth:Moolip)

**Comment by DereC4** [comment]
This was already added, as it not?

**Comment by SacredSpirit123** [comment]
> This was already added, as it not?

Was it? I remember the Moobloom, but not the Moolip.

moobloom: https://minecraft.gamepedia.com/Minecraft_Earth:Moobloom

moolip: https://minecraft.gamepedia.com/Minecraft_Earth:Moolip

**Comment by SacredSpirit123** [comment]
They’re two different mobs.

**Comment by SacredSpirit123** [comment]
I now see that it was indeed added. Does it do anything different with the milk potion?

**Comment by DereC4** [comment]
oh i'll add that then,  what type of drink would this be then?

**Comment by SacredSpirit123** [comment]
What does the moobloom potion that you added do? It says ‘rejuvenating drink’ on your wiki page.

**Comment by SacredSpirit123** [comment]
![726CBF98-C4B4-44D4-B286-7D02CC73CA59](https://user-images.githubusercontent.com/76529099/103445113-b6df5780-4c35-11eb-8f89-46f8d94907de.jpeg)
You also appear to have listed Moobloom, Moolip, AND Pink Moolip as three different mobs.

**Comment by DereC4** [comment]
oh it's the drink that you can get from buttercups it just heals you abit i think i have not looked it for a while

**Comment by SacredSpirit123** [comment]
Ok. Will you add one for the moo lip?

**Comment by DereC4** [comment]
ok i will do that next update
