### ISSUE TITLE
Rainbow Sheep cause crash (1.15.2)

### ISSUE THREAD

**Issue by EliotWL** [DereC4/derecearthmod#24]
🐛 **Bug Report**
📝 Description
Spawning in a rainbow sheep (or when one naturally spawns) the game crashes.

⭐ Describe the solution you'd like
Make the game not crash

🥟 How to reproduce?
Spawn a rainbow sheep.  Could possibly be due to the many mods I have installed currently?

🔢 Which version of the mod are you using?
Minecraft Earth Mod 1.15.2-1.5.0.0 
https://www.curseforge.com/minecraft/mc-mods/minecraft-earth-mod/files/3146587

❓ Anything else you would like to add? Comments? Info?
Here is the crash log

> ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 1/7/21 1:00 AM
> Description: Ticking entity
> 
> java.lang.NoClassDefFoundError: software/bernie/geckolib/entity/IAnimatedEntity
> 	at net.minecraftearthmod.procedures.IncrementRegrowthProcedure.executeProcedure(IncrementRegrowthProcedure.java:32) ~[?:?] {re:classloading}
> 	at net.minecraftearthmod.entity.RainbowSheepEntity$CustomEntity.func_70030_z(RainbowSheepEntity.java:225) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:368) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:charm:LivingEntity,xf:fml:caelus:coremodone}
> 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:179) ~[?:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.world.ClientWorld$$Lambda$15296/220837431.accept(Unknown Source) ~[?:?] {}
> 	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:149) ~[?:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1398) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.43.jar:31.2] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/83637545.call(Unknown Source) [forge-1.15.2-31.2.43.jar:31.2] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}
> Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib.entity.IAnimatedEntity
> 	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:104) ~[modlauncher-5.1.2.jar:?] {re:classloading}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
> 	... 24 more
> 	Suppressed: java.lang.ClassNotFoundException
> 		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:263) ~[modlauncher-5.1.2.jar:?] {}
> 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-5.1.2.jar:?] {re:classloading}
> 		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.2.jar:?] {re:classloading}
> 		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
> 		at net.minecraftearthmod.procedures.IncrementRegrowthProcedure.executeProcedure(IncrementRegrowthProcedure.java:32) ~[?:?] {re:classloading}
> 		at net.minecraftearthmod.entity.RainbowSheepEntity$CustomEntity.func_70030_z(RainbowSheepEntity.java:225) ~[?:?] {re:classloading}
> 		at net.minecraft.entity.Entity.func_70071_h_(Entity.java:368) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision,re:mixin,pl:accesstransformer:B}
> 		at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:charm:LivingEntity,xf:fml:caelus:coremodone}
> 		at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 		at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:179) ~[?:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
> 		at net.minecraft.client.world.ClientWorld$$Lambda$15296/220837431.accept(Unknown Source) ~[?:?] {}
> 		at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 		at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:149) ~[?:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
> 		at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1398) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 		at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 		at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
> 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.43.jar:31.2] {}
> 		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/83637545.call(Unknown Source) [forge-1.15.2-31.2.43.jar:31.2] {}
> 		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
> 		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
> 		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
> 		at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
> 		at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraftearthmod.procedures.IncrementRegrowthProcedure.executeProcedure(IncrementRegrowthProcedure.java:32)
> 	at net.minecraftearthmod.entity.RainbowSheepEntity$CustomEntity.func_70030_z(RainbowSheepEntity.java:225)
> 	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:368)
> 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2024)
> 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
> 	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:179)
> 	at net.minecraft.client.world.ClientWorld$$Lambda$15296/220837431.accept(Unknown Source)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft_earth_mod:rainbow_sheep (net.minecraftearthmod.entity.RainbowSheepEntity.CustomEntity)
> 	Entity ID: 2416
> 	Entity Name: Rainbow Sheep
> 	Entity's Exact location: 96.50, 65.00, 232.50
> 	Entity's Block location: World: (96,65,232), Chunk: (at 0,4,8 in 6,14; contains blocks 96,0,224 to 111,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Entity's Momentum: 0.00, 0.00, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.world.World.func_217390_a(World.java:536)
> 	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:149)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [ClientPlayerEntity['nofacekaiju'/255, l='MpServer', x=98.19, y=65.00, z=234.52]]
> 	Chunk stats: Client Chunk Cache: 841, 529
> 	Level dimension: DimensionType{minecraft:overworld}
> 	Level name: MpServer
> 	Level seed: 4698584309688023422
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: {}
> 	Level spawn location: World: (96,65,240), Chunk: (at 0,4,0 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 1089 game time, 1089 day time
> 	Known server brands: 
> 	Level was modded: false
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Server brand: forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
> 	at net.minecraft.client.main.Main.main(SourceFile:204)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/83637545.call(Unknown Source)
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.15.2
> 	Minecraft Version ID: 1.15.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1905962480 bytes (1817 MB) / 5692719104 bytes (5429 MB) up to 7456948224 bytes (7111 MB)
> 	CPUs: 16
> 	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m -XX:PermSize=256m
> 	ModLauncher: 5.1.2+70+master.2845bb9
> 	ModLauncher launch target: fmlclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
> 		/forge-1.15.2-31.2.43.jar object_holder_definalize PLUGINSERVICE 
> 		/forge-1.15.2-31.2.43.jar runtime_enum_extender PLUGINSERVICE 
> 		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
> 		/forge-1.15.2-31.2.43.jar capability_inject_definalize PLUGINSERVICE 
> 		/forge-1.15.2-31.2.43.jar runtimedistcleaner PLUGINSERVICE 
> 		/forge-1.15.2-31.2.43.jar fml TRANSFORMATIONSERVICE 
> 		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
> 		/MixinBootstrap-1.0.5.jar mixin PLUGINSERVICE 
> 		/MixinBootstrap-1.0.5.jar mixinbootstrap PLUGINSERVICE 
> 	FML: 31.2
> 	Forge: net.minecraftforge:31.2.43
> 	FML Language Providers: 
> 		javafml@31.2
> 		minecraft@1
> 		kotlinfml@1.5.2
> 	Mod List: 
> 		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
> 		flower-breeding-1.15.2-1.4.jar Lizzie's Flower Breeding {acmc@1.0 DONE}
> 		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
> 		XaerosWorldMap_1.11.6_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.11.6 DONE}
> 		JRFTL [1.15.2]-1.1.jar JRFTL {jrftl@1.1 DONE}
> 		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
> 		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
> 		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
> 		[1.15.2] Elementary Staffs 1.9.jar Elementary Staffs {element@1.9 DONE}
> 		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
> 		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
> 		Apotheosis-1.15.2-3.3.8.jar Apotheosis {apotheosis@3.3.8 DONE}
> 		mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
> 		ironshulkerboxes-1.15.2-4.0.1.jar Iron Shulker Boxes {ironshulkerbox@1.15.2-4.0.1 DONE}
> 		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
> 		PattysMoreStuff-Stable-1.2.7b.jar pattysmorestuff {pattysmorestuff@1.2.7b DONE}
> 		customcraftingtables-3.0.0-1.15.2.jar LDShadowLady's Custom Crafting Tables {customcraftingtables@3.0.0-1.15.2 DONE}
> 		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
> 		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE}
> 		resourcefulbees-1.15.2-0.3.8a.jar Resourceful Bees {resourcefulbees@1.15.2-0.3.8a DONE}
> 		lizardmod-1.15.2-1.2.1-10.jar Lizard Mod {lizardmod@1.15.2-1.2.1-10 DONE}
> 		crocmod-1.15.2-31.1.631.5.1-11.jar Crocodile Mod {crocmod@1.15.2-31.1.631.5.1-11 DONE}
> 		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
> 		Momos_Mod_v1.0.jar Momos Mod {momos_mod@1.0.0 DONE}
> 		fairylights-3.0.15-1.15.2.jar Fairy Lights {fairylights@3.0.15 DONE}
> 		EyesInTheDarkness-1.15.2-0.4.0.jar Eyes in the Darkness {eyesinthedarkness@0.4.0 DONE}
> 		SolarFluxReborn-1.15.2-15.2.3.jar Solar Flux Reborn {solarflux@15.2.3 DONE}
> 		randomenchants-3.1.1.jar Random Enchants {randomenchants@3.1.1 DONE}
> 		gaiadimension-1.15.2-1.2.3.jar The Gaia Dimension {gaiadimension@1.2.3 DONE}
> 		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
> 		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 DONE}
> 		camera-1.6.10.jar Camera Mod {camera@1.6.10 DONE}
> 		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
> 		additionalevents-1.1.jar Additional Events {additionalevents@1.1 DONE}
> 		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
> 		morevanillaarmor-1.15.2-1.2.jar MoreVanillaArmor {morevanillaarmor@1.15.2-1.2 DONE}
> 		mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
> 		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
> 		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
> 		Reeves'sFurnitureMod-3.1.1-1.15.2.jar Reeves's Furniture Mod {reevess_furniture_mod@3.1.1 DONE}
> 		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
> 		fortunate-2.8.1-MC-1.15.jar How Fortunate! {fortunate@2.8.1-MC-1.15 DONE}
> 		productivebees-1.15.2-0.5.2.6.jar Productive Bees {productivebees@1.15.2-0.5.2.6 DONE}
> 		HearthstoneMod-1.15.2-0.5.1.jar Hearthstone Mod {hearthstonemod@0.5.1 DONE}
> 		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
> 		hatstands-1.0.1-1.15.2.jar Hat Stands {hatstands@1.0.1 DONE}
> 		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
> 		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
> 		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE DONE}
> 		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
> 		caelus-FORGE-1.15.2-2.0-beta4.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta4 DONE}
> 		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
> 		Bloomful-1.15.2-1.4.1.jar Bloomful {bloomful@NONE DONE}
> 		WAWLA-1.15.2-3.0.4.jar WAWLA {wawla@3.0.4 DONE}
> 		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
> 		WallpaperCraft-1.15.2-1.2.4.jar Wallpapercraft {wallpapercraft@1.2.4 DONE}
> 		WallpapercraftSlabs-1.15.2-1.1.0.jar Wallpapercraft - Slabs! {wallpapercraftslabs@1.1.0 DONE}
> 		WallpapercraftStairs-1.15.2-1.1.1.jar Wallpapercraft - Stairs {wallpapercraftstairs@1.1.1 DONE}
> 		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 DONE}
> 		comforts-FORGE-1.15.2-2.0.0.4.jar Comforts {comforts@FORGE-1.15.2-2.0.0.4 DONE}
> 		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
> 		BotanyPots-1.15.2-2.0.29.jar BotanyPots {botanypots@2.0.29 DONE}
> 		betteranimalsplus-1.15.2-10.1.0.jar Better Animals Plus {betteranimalsplus@10.1.0 DONE}
> 		TinyMobFarm-1.15.2-1.0.8.jar Tiny Mob Farm {tinymobfarm@1.0.8 DONE}
> 		bedspreads-FORGE-1.15.2-3.0.0.1.jar Bedspreads {bedspreads@FORGE-1.15.2-3.0.0.1 DONE}
> 		dads-sewing-1.15.2-v2.jar Dad's Sewing {dads_sewing@1.0.0 DONE}
> 		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
> 		forge-1.15.2-31.2.43-universal.jar Forge {forge@31.2.43 DONE}
> 		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
> 		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
> 		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
> 		SimpleDivingGear-4.0.1 mc 1.15.2.jar Simple Diving Gear {simpledivegear@4.0.1 mc 1.15.2 DONE}
> 		forge-1.15.2-31.2.43-client.jar Minecraft {minecraft@1.15.2 DONE}
> 		cofh_core-1.15.2-1.0.2.jar CoFH Core {cofh_core@1.0.2 DONE}
> 		thermal-1.15.2-1.0.2.jar Thermal Series {thermal@1.0.2 DONE}
> 		thermal_expansion-1.15.2-1.0.2.jar Thermal Expansion {thermal_expansion@1.0.2 DONE}
> 		thermal_locomotion-1.15.2-1.0.0.jar Thermal Locomotion {thermal_locomotion@1.0.0 DONE}
> 		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
> 		turtlemod-1.15.1-1.2.0-6.jar Turtle Mod {turtlemod@1.15.1-1.2.0-6 DONE}
> 		EnchantmentDescriptions-1.15.2-2.0.9.jar EnchantmentDescriptions {enchdesc@2.0.9 DONE}
> 		pandoras_creatures-1.15.2-1.0.1.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.1 DONE}
> 		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
> 		compactores-1.15.2-2.1.4.jar Compact Ores {compactores@2.1.4 DONE}
> 		archers_paradox-1.15.2-1.0.0.jar Archer's Paradox {archers_paradox@1.0.0 DONE}
> 		omgourd-1.15.2-1.0.0.jar Oh My Gourd {omgourd@1.0.0 DONE}
> 		Craftable Saddles [1.15.2]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
> 		SpartanShields-1.15.2-2.1.0.jar Spartan Shields {spartanshields@2.1.0 DONE}
> 		Xaeros_Minimap_20.30.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.30.1 DONE}
> 		WallpapercraftWalls-1.15.2-1.1.0.jar Wallpapercraft - Walls! {wallpapercraftwalls@1.1.0 DONE}
> 		rats-5.3.2-1.15.2.jar Rats {rats@5.3.2 DONE}
> 		lava-monster-1.15.2-1.0.5.jar Lava Monster {lava_monster@1.0.5 DONE}
> 		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
> 		polymorph-FORGE-1.15.2-0.10.jar Polymorph {polymorph@FORGE-1.15.2-0.10 DONE}
> 		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
> 		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
> 		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
> 		LibraryEx-1.15.2-3.0.1.jar LibraryEx {libraryex@3.0.1 DONE}
> 		Skye's Bakery 2.1.1 for MC1.15.2.jar Skye's Bakery {skyes_bakery@2.1.1 DONE}
> 		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
> 		connectedglass-1.0.6-mc1.15.jar Connected Glass {connectedglass@1.0.6 DONE}
> 		MinecraftEarthMod-1.5.0.0.jar Minecraft Earth Mod {minecraft_earth_mod@1.5.0.0 DONE}
> 		MysticalWildlife.jar Mystical Wildlife 1.15.2 Fork {mysticalwildlife@1.0.0.0 DONE}
> 		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
> 	Launched Version: forge-31.2.43
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: AMD Radeon RX 5700 XT GL version 4.6.14736 Compatibility Profile Context 20.8.1 27.20.2001.13001, ATI Technologies Inc.
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor

**Comment by nofacekaiju** [comment]
Hi, I've been having the same issue as @EliotWL and I did a little digging. I think it might be due to a small typo? The line of the stacktrace that caught my attention was

`net.minecraftearthmod.procedures.IncrementRegrowthProcedure.executeProcedure(IncrementRegrowthProcedure.java:32)`

From what I understand this mod uses the geckolib in order to make the sheep's wool animated, and specifically the problem is in the file "IncrementRegrowthProcedure" under the procedures folder. I decompiled it and it seems like it's calling to import

`software.bernie.geckolib.entity.IAnimatedEntity`

While in the example file [here](https://github.com/bernie-g/geckolib/blob/develop/src/main/java/software/bernie/example/entity/GeoExampleEntity.java) it's referred to as "geckolib3".

Considering I don't actually have access to the source or anything like that, this is pretty much just an educated guess. But I figure'd it might be a good place to start. Thanks.

**Comment by DereC4** [comment]
I'll take a look at this this weekend, although it looks like a tickingentity thing too (happened to me when I used a mod that created bacteria that destroyed the world; it would eventually crash your computer)
I'll try to fix this next update; sorry for the issues

**Comment by DereC4** [comment]
fixed, and you are both in credits now!
