### ISSUE TITLE
Skeleton dog sitting and tail

### ISSUE THREAD

**Issue by JBalina** [DereC4/derecearthmod#29]
🎁 **Feature Request**

📝 Description
It's currently kinda hard to distinguish if your skeledog is supposed to be following you or not, it doesn't even necessarily have to be sitting but a way to tell if it's in follow mode would be useful. Also it would be nice if the tail angle changed accordingly to its health similar to how vanilla minecraft dogs work.

❓ Anything else you would like to add? Comments? Info?
You're awesome!

**Comment by DereC4** [comment]
Interesting. Perhaps particles?

**Comment by JBalina** [comment]
Yes! Something like that would surely be helpful

**Comment by JBalina** [comment]
Additionally, idk if this will be difficult but maybe the particles can work similar to collars on normal dogs in that the particle color can change if you use a dye on the skeledog

**Comment by DereC4** [comment]
I'll look into this

**Comment by DereC4** [comment]
the particle stuff and better interaction (makes sounds too) is added i know i didnt get the animation and stuffb ut if you want to open a new issues for those that would be fine too sorry it's am hours here and im kinda tired

**Comment by DereC4** [comment]
Also you've been added to credits
