### ISSUE TITLE
suggestion: let chicken variants lay eggs

### ISSUE THREAD

**Issue by LuyQyu** [DereC4/derecearthmod#3]
let them lay normal eggs. so there is no need for new items, but a chicken variant could be mother of a vanilla chicken. maybe introduce a chance, that an egg can spawn a variant (I personally don't think thats needed, since the fun about the mod is to find the variants in the world)

**Comment by Hillionliat** [comment]
If spawning variant from egg i would like to be in rareness, the some variants would be common and some variants rare, except of spawning cluckshrooms as it's mutated chicken not a variant

**Comment by LuyQyu** [comment]
the variant spawn from eggs is somewhat logic since they are all chicken. but then again you can't crossbreed any chicken, cause they are different mobs. so I would prefer it it's just a vanilla egg with normal vanilla functionallity (similar to the milk from the cow variants).

**Comment by Hillionliat** [comment]
Then I think eggs should spawn the chicken variant corresponding to the parent chicken variant 
like amber chicken spawns eggs that spawn amber chickens

**Comment by LuyQyu** [comment]
so I posted this suggestion, because I couldn't find any normal chicken in my little modpack I threw together. but I really needed eggs for recepies and magic stuff. when you introduce new eggs corresponding to each variant of chicken, you have to make sure they work with all other mods which is a hassle. 

the beauty of this mod is pretty straight forward: more variants and life in your minecraft world. I think it doesn't have to be too complicated.

I'm just looking for eggs...

**Comment by DereC4** [comment]
Wdym eggs just like normal chickens eggs?

**Comment by LuyQyu** [comment]
yes. just chicken eggs

**Comment by DereC4** [comment]
okay

**Comment by DereC4** [comment]
This is now working, chickens lay eggs at 5-12 minute intervals! Thanks for suggesting!
