### ISSUE TITLE
Furnace Golem Suggestion

### ISSUE THREAD

**Issue by Hillionliat** [DereC4/derecearthmod#4]
Furnace Golem acts like normal Golem with few additional features when he gets into attack form he has animated texture of him being powered up, he also can set enemies on fire by punching them or doing like a hug gesture, also his hair like hat goes forward a little
![2020-11-17 23-51-38](https://user-images.githubusercontent.com/52645174/99455040-f07f2c00-292f-11eb-9b46-083ac1e5835b.png)

Video - https://youtu.be/uNuWzcyoAnI

**Comment by Hillionliat** [comment]
![furnace_golem_blink](https://user-images.githubusercontent.com/52645174/99456685-713f2780-2932-11eb-99ea-d3748b1c3297.png)
![furnace_golem_flames_layer_anim_1](https://user-images.githubusercontent.com/52645174/99456689-71d7be00-2932-11eb-9433-5e37b9014fad.png)
![furnace_golem_flames_layer_anim_2](https://user-images.githubusercontent.com/52645174/99456690-72705480-2932-11eb-9479-65738c8b311c.png)
![furnace_golem_flames_layer_anim_3](https://user-images.githubusercontent.com/52645174/99456691-72705480-2932-11eb-863e-a150a087533a.png)
![furnace_golem_flames_layer_anim_4](https://user-images.githubusercontent.com/52645174/99456694-72705480-2932-11eb-8905-e1f4b1601f19.png)
![furnace_golem_flames_layer_anim_5](https://user-images.githubusercontent.com/52645174/99456696-7308eb00-2932-11eb-96a1-709241168acb.png)
![furnace_golem_flames_layer_anim_6](https://user-images.githubusercontent.com/52645174/99456697-7308eb00-2932-11eb-9231-aa69fdd68748.png)
![furnace_golem_angry](https://user-images.githubusercontent.com/52645174/99456698-73a18180-2932-11eb-92cf-e8bc0efb0fda.png)

**Comment by Hillionliat** [comment]
![furnace_golem_angry](https://user-images.githubusercontent.com/52645174/99470556-9725f580-294d-11eb-9ab0-00a16a77b031.png)
![furnace_golem_flames_layer_anim_1](https://user-images.githubusercontent.com/52645174/99470571-9c834000-294d-11eb-8265-b6192e7f62d5.png)
![furnace_golem_flames_layer_anim_2](https://user-images.githubusercontent.com/52645174/99470579-9f7e3080-294d-11eb-9abb-562ad107d548.png)
![furnace_golem_flames_layer_anim_3](https://user-images.githubusercontent.com/52645174/99470586-a1e08a80-294d-11eb-8d42-7e188bafe5bd.png)
![furnace_golem_flames_layer_anim_4](https://user-images.githubusercontent.com/52645174/99470590-a442e480-294d-11eb-9dba-991993c91073.png)
![furnace_golem_flames_layer_anim_5](https://user-images.githubusercontent.com/52645174/99470598-a60ca800-294d-11eb-952e-3290c52aa93c.png)
![furnace_golem_flames_layer_anim_6](https://user-images.githubusercontent.com/52645174/99470604-a86f0200-294d-11eb-87b1-17531e952099.png)

**Comment by DereC4** [comment]
I'll take this into consideration but it wont be added immediately

**Comment by Hillionliat** [comment]
> I'll take this into consideration but it wont be added immediately

BTW Do you want me to put mobs that are not in this mod like viler witch and others

**Comment by DereC4** [comment]
sure

**Comment by DereC4** [comment]
I'm not sure if im doing this right but i've changed the texture to accomodate for the "hat" and changed the model as well
