### ISSUE TITLE
Bug report Moobloom don't plant flowers also buttercup on head is flat

### ISSUE THREAD

**Issue by Hillionliat** [DereC4/derecearthmod#8]
it doesn't seem like they do plant flowers not only that they are always running in panic like they've been hit also buttercup on mooblooms head is 2D
![2020-11-24_00 38 23](https://user-images.githubusercontent.com/52645174/100023566-dfca2c80-2ded-11eb-80ff-a7e60badb630.png)

**Comment by DereC4** [comment]
I will try to fix the model today, the behavior part I am seriously not sure what is up because it's not acting like that for my Minecraft

**Comment by DereC4** [comment]
Model is fixed; will be released in next update

**Comment by Hillionliat** [comment]
Here is the video showing how they are acting and how they should act comparing to vanilla cow
https://youtu.be/3z4JoTvr2S4

**Comment by DereC4** [comment]
Okay, I'm not sure why this is happening though. Do you have any other mods active?

**Comment by Hillionliat** [comment]
No it's vanilla minecraft with forge intalled

**Comment by DereC4** [comment]
Not intentional; they just didnt have the option to stare at the player like cows did which I will add in next update. Thanks

**Comment by DereC4** [comment]
As for your thing saying that they dont plant, I tested it and i have proof that they do it's just that the plant rate is pretty low.

**Comment by DereC4** [comment]
[https://i.imgur.com/1V4AoB5.png](url)
[https://i.imgur.com/3huebu5.png](url)

**Comment by DereC4** [comment]
yeehaw
